### ISSUE TITLE
🐛 : Error creating bean with name 'ldapContextSource'

### ISSUE THREAD

**Issue by solox2** [gaia-app/gaia#596]
**Describe the bug**
Running docker-compose build and main gaia app won't boot up

**To Reproduce**
1.  Docker-compose up -d
2.  Gaia container crashes

**Expected behavior**
Container should stay up and gaia app should be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/39422704/115443388-0a1aed00-a1c8-11eb-8c62-29556b3a8691.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker Version: 20.10.6

**Comment by juwit** [comment]
Hello :wave: and thank you for your contribution !

This issue seems to be related with our recent upgrade to openjdk-16 for the java runtime.

Here is a workaround, while we are working on this to find a real fix :

 * replace the 6th line of the Dockerfile with this : 

```
FROM openjdk:15-jdk
```

(was openjdk:16-jdk)

Gaia should start correctly :)

**Comment by juwit** [comment]
The issue is resolved :tada:, you can update your `master` branch to get the latest version of the `Dockerfile`
